[package]
name = "pq"
version = "0.9.5"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
description = "jq for protobuf"
repository = "https://github.com/sevagh/pq"
documentation = "https://github.com/sevagh/pq"
readme = "README.md"
license = "MIT"
keywords = ["protobuf", "serde"]

[dependencies]
serde = "1.0.10"
serde-value = "0.5.0"
erased_serde_json = { path = "erased-serde-json", version = "0.1.0" }
serde_json = "1.0.3"
serde-protobuf = "0.6.0"
protobuf = "1.4.1"
libc = "0.2.26"
stream_delimit = { path = "stream-delimit", version = "0.4.2" }
clap = "2.26.0"
error-chain = "0.10.0"

[dev-dependencies]
assert_cli = "0.5.3"

[features]
default = ["stream_delimit/with_kafka"]

[workspace]
members = ["stream-delimit", "erased-serde-json"]

[profile.release]
debug = true
lto = true
panic = "abort"
