[package]
name = "pq"
version = "0.3.4"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
description = "jq for protobuf"
repository = "https://github.com/sevagh/pqrs"
documentation = "http://pqrs.sevag.xyz"
readme = "./README.md"
license = "MIT"
keywords = ["protobuf", "serde"]

[badges]
travis-ci = { repository = "https://travis-ci.org/sevagh/pqrs", branch = "master" }

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
serde = "0.9.12"
serde-value = "0.4.0"
serde_json = "0.9.9"
serde-protobuf = "0.5"
protobuf = "1.2.1"
