[package]
name = "pq"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dev-dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"
