[package]
name = "pq"
version = "0.7.2"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
description = "jq for protobuf"
repository = "https://github.com/sevagh/pq"
documentation = "https://github.com/sevagh/pq"
readme = "./README.md"
license = "MIT"
keywords = ["protobuf", "serde"]

[dependencies]
serde = "1.0.2"
serde-value = "0.5.0"
serde_json = "1.0.2"
serde-protobuf = "0.5.0"
protobuf = "1.2.1"
libc = "0.2.22"
stream_delimit = "0.3.1"
clap = "2.24.2"

[replace]
"serde-protobuf:0.5.0" = { git = 'https://github.com/sevagh/rq' }

[profile.release]
debug = true
lto = true
panic = "abort"
