[package]
name = "pq"
version = "0.9.2"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
description = "jq for protobuf"
repository = "https://github.com/sevagh/pq"
documentation = "https://github.com/sevagh/pq"
readme = "README.md"
license = "MIT"
keywords = ["protobuf", "serde"]

[dependencies]
serde = "1.0.10"
serde-value = "0.5.0"
erased_serde_json = { git = "https://github.com/sevagh/erased-serde-json" }
serde_json = "1.0.2"
serde-protobuf = "0.6.0"
protobuf = "1.4.1"
libc = "0.2.26"
stream_delimit = { path = "stream_delimit", version = "0.4.1" }
clap = "2.26.0"
error-chain = "0.10.0"

[features]
default = ["stream_delimit/with_kafka"]

[workspace]
members = ["stream_delimit"]

[profile.release]
debug = true
lto = true
panic = "abort"
