[package]
name = "pq"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
serde-protobuf = "0.5"
serde = "0.9.12"
serde-value = "0.4.0"
protobuf = "1.2.1"
